In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("Iris.csv") 
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [3]:
df.head()
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [4]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='str')

In [5]:
df.SepalLengthCm.mean()

np.float64(5.843333333333334)

In [6]:
print("SepalLengthCm mean = ",+df.SepalLengthCm.mean())

SepalLengthCm mean =  5.843333333333334

In [7]:
df.groupby(['Species']).count()

                 Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
Iris-setosa      50             50            50             50            50
Iris-versicolor  50             50            50             50            50
Iris-virginica   50             50            50             50            50

In [8]:
df.groupby(['Species']).SepalLengthCm.mean()

Species
Iris-setosa        5.006
Iris-versicolor    5.936
Iris-virginica     6.588
Name: SepalLengthCm, dtype: float64

In [9]:
print("SepalLengthCm Mean of ",+df.groupby(['Species']).SepalLengthCm.mean())

SepalLengthCm Mean of  Species
Iris-setosa        5.006
Iris-versicolor    5.936
Iris-virginica     6.588
Name: SepalLengthCm, dtype: float64

In [10]:
print("SepalWidthCm Mean of ", df.groupby(['Species']).SepalWidthCm.mean())

SepalWidthCm Mean of  Species
Iris-setosa        3.418
Iris-versicolor    2.770
Iris-virginica     2.974
Name: SepalWidthCm, dtype: float64

In [11]:
print("PetalLengthCm Mean of ",+df.groupby(['Species']).PetalLengthCm.mean())

PetalLengthCm Mean of  Species
Iris-setosa        1.464
Iris-versicolor    4.260
Iris-virginica     5.552
Name: PetalLengthCm, dtype: float64

In [12]:
print("PetalWidthCm Mean of",+df.groupby(['Species']).PetalWidthCm.mean())

PetalWidthCm Mean of Species
Iris-setosa        0.244
Iris-versicolor    1.326
Iris-virginica     2.026
Name: PetalWidthCm, dtype: float64

In [13]:
print("SepalLengthCm Standard Deviation of ",+df.groupby(['Species']).SepalLengthCm.std())

SepalLengthCm Standard Deviation of  Species
Iris-setosa        0.352490
Iris-versicolor    0.516171
Iris-virginica     0.635880
Name: SepalLengthCm, dtype: float64

In [14]:
print("SepalWidthCm Standard Deviation of ", df.groupby(['Species']).SepalWidthCm.std())

SepalWidthCm Standard Deviation of  Species
Iris-setosa        0.381024
Iris-versicolor    0.313798
Iris-virginica     0.322497
Name: SepalWidthCm, dtype: float64

In [15]:
print("PetalLengthCm Standard Deviation of ",+df.groupby(['Species']).PetalLengthCm.std())

PetalLengthCm Standard Deviation of  Species
Iris-setosa        0.173511
Iris-versicolor    0.469911
Iris-virginica     0.551895
Name: PetalLengthCm, dtype: float64

In [16]:
print("PetalWidthCm Standard Deviation of",+df.groupby(['Species']).PetalWidthCm.std())

PetalWidthCm Standard Deviation of Species
Iris-setosa        0.107210
Iris-versicolor    0.197753
Iris-virginica     0.274650
Name: PetalWidthCm, dtype: float64

In [17]:
print("SepalLengthCm Standard Deviation of ",+df.groupby(['Species']).SepalLengthCm.describe())

SepalLengthCm Standard Deviation of                   count   mean       std  min    25%  50%  75%  max
Species
Iris-setosa       50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
Iris-versicolor   50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
Iris-virginica    50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

In [18]:
print("SepalWidthCm Description of ", df.groupby(['Species']).SepalWidthCm.describe())

SepalWidthCm Description of                   count   mean       std  min    25%  50%    75%  max
Species
Iris-setosa       50.0  3.418  0.381024  2.3  3.125  3.4  3.675  4.4
Iris-versicolor   50.0  2.770  0.313798  2.0  2.525  2.8  3.000  3.4
Iris-virginica    50.0  2.974  0.322497  2.2  2.800  3.0  3.175  3.8

In [19]:
print("PetalLengthCm Description of ",+df.groupby(['Species']).PetalLengthCm.describe())

PetalLengthCm Description of                   count   mean       std  min  25%   50%    75%  max
Species
Iris-setosa       50.0  1.464  0.173511  1.0  1.4  1.50  1.575  1.9
Iris-versicolor   50.0  4.260  0.469911  3.0  4.0  4.35  4.600  5.1
Iris-virginica    50.0  5.552  0.551895  4.5  5.1  5.55  5.875  6.9

In [20]:
print("PetalWidthCm Description of",+df.groupby(['Species']).PetalWidthCm.describe())

PetalWidthCm Description of                  count   mean       std  min  25%  50%  75%  max
Species
Iris-setosa       50.0  0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor   50.0  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica    50.0  2.026  0.274650  1.4  1.8  2.0  2.3  2.5

In [21]:
df.groupby("Species").describe().sum()

Id             count    150.000000
               mean     226.500000
               std       43.732139
               min      153.000000
               25%      189.750000
               50%      226.500000
               75%      263.250000
               max      300.000000
SepalLengthCm  count    150.000000
               mean      17.530000
               std        1.504540
               min       14.100000
               25%       16.625000
               50%       17.400000
               75%       18.400000
               max       20.700000
SepalWidthCm   count    150.000000
               mean       9.162000
               std        1.017319
               min        6.500000
               25%        8.450000
               50%        9.200000
               75%        9.850000
               max       11.600000
PetalLengthCm  count    150.000000
               mean      11.276000
               std        1.195317
               min        8.500000
               25%       10.500000
               50%       11.400000
               75%       12.050000
               max       13.900000
PetalWidthCm   count    150.000000
               mean       3.596000
               std        0.579612
               min        2.500000
               25%        3.200000
               50%        3.500000
               75%        4.100000
               max        4.900000
dtype: float64